# Generated by Django 3.1.6 on 2021-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_aplicacoes', models.TextField(null=True)),
                ('mes_aplicacoes', models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], default='Janeiro', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_despesas', models.TextField(null=True)),
                ('mes_despesas', models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], default='Janeiro', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_salario', models.TextField(null=True)),
                ('mes_receitas', models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], default='Janeiro', max_length=10)),
            ],
        ),
    ]
